apiVersion: v1
kind: Namespace
metadata:
  name: fatih-bilgi

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis-replicaset
  namespace: fatih-bilgi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  namespace: fatih-bilgi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: fatih-bilgi
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: strapi-replicaset
  namespace: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
        - name: strapi
          image: strapi/strapi:latest
          ports:
            - containerPort: 1337
          env:
            - name: DATABASE_CLIENT
              value: redis
            - name: DATABASE_HOST
              value: redis-service.fatih-bilgi
            - name: DATABASE_PORT
              value: "6379"

---

apiVersion: v1
kind: Service
metadata:
  name: strapi-service
  namespace: fatih-bilgi
spec:
  selector:
    app: strapi
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337
